### ISSUE TITLE
[Question] Why force to concatenate PHP_EOL ?

### ISSUE THREAD

**Issue by flavienbwk** [wujunze/php-cli-color#6]
Hello,

My question is about the  `PHP_EOL` you show in your README.md as example.

Do we need to always concatenate it ?
Why not automatically add it in in the `getColoredString()` method ?

Thank you.

**Comment by wujunze** [comment]
Hello,
This is a great suggestion. You can make one Pull request  to fix it 
Thank you. @flavienbwk

**Comment by flavienbwk** [comment]
#7

**Comment by wujunze** [comment]
relead v2.2 
https://packagist.org/packages/wujunze/php-cli-color#v2.2

**Comment by nachomozo** [comment]
I'm not sure if this is a great feature. How can I use 2 colors in the same line now? Maybe it could be optional?

Thank you.

**Comment by wujunze** [comment]
That's a great suggestion.  
You can make one Pull request to fix it
Thank you. @nachomozo

**Comment by wujunze** [comment]
I don't think you need to remove the PHP_EOL configuration parameter what do you think
Thanks  you  @flavienbwk

**Comment by flavienbwk** [comment]
Hello @wujunze, as another user said, the problem with the library forcing to put the PHP_EOL is we can't concatenate colorful strings. So maybe it is more correct to let the user choose for what he wants (if he wants, he adds the PHP_EOL, but by default, it's not added).

**Comment by wujunze** [comment]
Oh  I fixed https://github.com/wujunze/php-cli-color/releases/tag/v2.4  @flavienbwk 

Thank you
